import Head from "next/head";
import Image from "next/image";
import React from "react";
import logo from "../public/images/logo.svg";
import s from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello</h1>
    </>
  );
}
